name: DotMan
api-version: 1.13
folia-supported: true
main: net.minevn.dotman.DotMan
version: '${version}'
author: MineVN
depend: [ MineVNLib, PlayerPoints ]
softdepend: [ PlaceholderAPI ]
commands:
  dotman:
    permission: dotman.admin
  topnap:
    permission: dotman.topnap
  napthe:
