name: DotMan
api-version: 1.20
main: net.minevn.dotman.DotMan
version: '${version}'
author: MineVN
depend: [ MineVNLib, PlayerPoints, PlaceholderAPI ]
commands:
  dotman:
    permission: dotman.admin
  topnap:
    permission: dotman.topnap
  napthe: