name: Build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v5.2.0
        with:
          distribution: temurin
          java-version: 8
          cache: "gradle"     
      - name: Get MineVNLib version
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: minevn
          repo: minevn-library
        id: minevnlib-plugin
      - name: Build DotMan & download MineVNLib
        run: |
          chmod +x ./gradlew
          ./gradlew assemble
          mkdir -p target
          cp ./dotman-plugin/build/libs/DotMan.jar ./target/DotMan.jar
          wget -O ./target/MineVNLib.jar "https://github.com/minevn/minevn-library/releases/download/${{ steps.minevnlib-plugin.outputs.release }}/MineVNLib.jar"
      - name: Upload build artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: "DotMan"
          path: ./target/